esphome:
  name: espplayer
  friendly_name: ESPPlayer
  on_boot:
    priority: -100
    then:
      - dfplayer.set_volume: 25
      - delay: 500ms      
      - dfplayer.stop:

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid2
  password: !secret wifi_password2

  # Set up a wifi access point
  ap: {}

web_server:
  
captive_portal:

uart:
  id: uart_bus
  tx_pin: GPIO27
  rx_pin: GPIO26
  baud_rate: 9600

dfplayer:
  uart_id: uart_bus
  on_finished_playback:
    then:
      - logger.log: "Lecture terminée."

script:
  - id: play_music_if_allowed
    mode: restart  # Empêche l’exécution simultanée
    then:
      - dfplayer.play_next:
      - delay: 1s  # Bloque toute nouvelle exécution pendant 1 secondes

button:
  - platform: template
    name: "Musique stop"
    on_press:
      - dfplayer.stop

  - platform: template
    name: "Musique suivant"
    on_press:
      - dfplayer.play_next

  - platform: template
    name: "Musique précédent"
    on_press:
      - dfplayer.play_previous

number:
  - platform: template
    name: "Musique Volume"
    id: volume_dfplayer
    min_value: 0
    max_value: 30
    step: 1
    initial_value: 20
    optimistic: true
    set_action:
      then:
        - dfplayer.set_volume: !lambda 'return (int)x;'

output:
  - platform: gpio
    pin: GPIO02
    id: internal_led

  - platform: gpio
    pin: GPIO17
    id: external_led

light:
  - platform: binary
    name: "LED externe"
    output: external_led
    id: my_external_led

  - platform: binary
    name: "LED interne"
    output: internal_led
    id: my_internal_led

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT_PULLUP  # Active la résistance pull-up interne
      inverted: false       # Inversion logique (0 quand appuyé)
    name: "Capteur bouton"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      then:
        - if:
            condition:
              not:
                script.is_running: play_music_if_allowed
            then:
              - script.execute: play_music_if_allowed
        - light.turn_on: my_internal_led
        - light.turn_on: my_external_led
        - delay: 200ms
        - light.turn_off: my_internal_led
        - light.turn_off: my_external_led
